ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "dateOfBirth" TIMESTAMP(3);
ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "recoveryType" TEXT;
ALTER TABLE "Profile" ADD COLUMN IF NOT EXISTS "careProvider" TEXT;
