export const ErrorCodes = {
    AUTH_GENERIC: 'AUTH_GENERIC',
    AUTH_CREDENTIALS: 'AUTH_CREDENTIALS',
    AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
    AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
    AUTH_RESET_PASSWORD: 'AUTH_RESET_PASSWORD',
    AUTH_CONFLICT: 'AUTH_CONFLICT',
    AUTH_OAUTH: 'AUTH_OAUTH',
    NOT_FOUND: 'NOT_FOUND',
    CONFLICT: 'CONFLICT',
    VALIDATION_GENERIC: 'VALIDATION_GENERIC',
    VALIDATION_OTP: 'VALIDATION_OTP',
    VALIDATION_ZOD: 'VALIDATION_ZOD',
    INTERNAL_ERROR: 'INTERNAL_ERROR'
} as const

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes]
