UPDATE "Tag" SET "nameHe" = 'שבר' WHERE slug = 'fracture';
UPDATE "Tag" SET "nameHe" = 'ניתוח' WHERE slug = 'surgery';
UPDATE "Tag" SET "nameHe" = 'פציעת עמוד שדרה' WHERE slug = 'spinal-injury';
UPDATE "Tag" SET "nameHe" = 'שבץ מוחי' WHERE slug = 'stroke';
UPDATE "Tag" SET "nameHe" = 'כאב כרוני' WHERE slug = 'chronic-pain';
UPDATE "Tag" SET "nameHe" = 'ניידות' WHERE slug = 'mobility';
UPDATE "Tag" SET "nameHe" = 'מסע ההחלמה' WHERE slug = 'recovery-journey';
UPDATE "Tag" SET "nameHe" = 'פיזיותרפיה' WHERE slug = 'physical-therapy';
UPDATE "Tag" SET "nameHe" = 'ריפוי בעיסוק' WHERE slug = 'occupational-therapy';
UPDATE "Tag" SET "nameHe" = 'פעילות גופנית' WHERE slug = 'exercise';
UPDATE "Tag" SET "nameHe" = 'מתיחות' WHERE slug = 'stretching';
UPDATE "Tag" SET "nameHe" = 'הליכה' WHERE slug = 'walking';
UPDATE "Tag" SET "nameHe" = 'ניהול כאב' WHERE slug = 'pain-management';
UPDATE "Tag" SET "nameHe" = 'חרדה' WHERE slug = 'anxiety';
UPDATE "Tag" SET "nameHe" = 'מוטיבציה' WHERE slug = 'motivation';
UPDATE "Tag" SET "nameHe" = 'שחיקה' WHERE slug = 'burnout';
UPDATE "Tag" SET "nameHe" = 'בדידות' WHERE slug = 'loneliness';
UPDATE "Tag" SET "nameHe" = 'תסכול' WHERE slug = 'frustration';
UPDATE "Tag" SET "nameHe" = 'ביטחון עצמי' WHERE slug = 'confidence';
UPDATE "Tag" SET "nameHe" = 'שינה' WHERE slug = 'sleep';
UPDATE "Tag" SET "nameHe" = 'תזונה' WHERE slug = 'nutrition';
UPDATE "Tag" SET "nameHe" = 'קשיבות' WHERE slug = 'mindfulness';
UPDATE "Tag" SET "nameHe" = 'תמיכת משפחה' WHERE slug = 'family-support';
UPDATE "Tag" SET "nameHe" = 'שגרות' WHERE slug = 'routines';
UPDATE "Tag" SET "nameHe" = 'חזרה לעבודה' WHERE slug = 'work-return';
UPDATE "Tag" SET "nameHe" = 'סיפור הצלחה' WHERE slug = 'success-story';
UPDATE "Tag" SET "nameHe" = 'עצה' WHERE slug = 'advice';
UPDATE "Tag" SET "nameHe" = 'שאלת מתחיל' WHERE slug = 'beginner-question';
UPDATE "Tag" SET "nameHe" = 'בריאות נפשית' WHERE slug = 'mental-health';
UPDATE "Tag" SET "nameHe" = 'החלמה' WHERE slug = 'recovery';
UPDATE "Tag" SET "nameHe" = 'בריאות גופנית' WHERE slug = 'physical-health';
UPDATE "Tag" SET "nameHe" = 'טיפים לבריאות' WHERE slug = 'wellness-tips';
